spring.application.name = LetsGo

spring.datasource.url=jdbc:mysql://localhost:3306/letsgo
spring.datasource.username=root
spring.datasource.password=Root@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret = LTXJwp0JVJdGTLVhkZs9Gk70uAW+/ECX3uKhVXeYI68=
#24 hours
jwt.expiration = 86400000